# Generated by Django 5.2.5 on 2025-08-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_phone_alter_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='phone',
        ),
        migrations.AddField(
            model_name='hospital',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='hospitals.doctor'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospitals/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
